### ISSUE TITLE
Interested in using this package in PlayCover

### ISSUE THREAD

**Issue by amirsaam** [paradiseduo/inject#1]
Howdy!

We at [PlayCover](https://github.com/PlayCover/PlayCover) are interested in using this package but we need to have a discussion about it.
Please contact us in [PlayCover Discord Server](https://discord.gg/RNCHsQHr3S) to talk about it.

Regards,

**Comment by paradiseduo** [comment]
Thank you for your attention.
Is there anything you want to know?

**Comment by amirsaam** [comment]
There is a lot of things we need to discuss but with main developers not particularly with me.
So it will be helpful if you come to our discord server or open an issue on our main repo to let people do actually communicate.

**Comment by ohaiibuzzle** [comment]
Basically, we may end up replacing the current Mach-O injection component in PlayCover, which is right now [optool](https://github.com/alexzielenski/optool), that has gone unmaintained for quite some time and uses ObjC instead of Swift, which not all of us are too familiar with

**Comment by IsaacMarovitz** [comment]
@paradiseduo Our main questions are:
1. Could you add a license to the repo e.g. MIT or something along those lines? Without a license, it becomes legally ambiguous for us to use this package
2. Would it be possible to add the ability to *remove* load commands as well as insert them, as that is a feature we currently need for PlayCover

**Comment by paradiseduo** [comment]
> @paradiseduo Our main questions are:
> 
> 1. Could you add a license to the repo e.g. MIT or something along those lines? Without a license, it becomes legally ambiguous for us to use this package
> 2. Would it be possible to add the ability to _remove_ load commands as well as insert them, as that is a feature we currently need for PlayCover

This software is released under the GPL-3.0 license.
Now I add license.

remove load commands feature under development

**Comment by IsaacMarovitz** [comment]
Do you have an ETA on the removal feature?

**Comment by IsaacMarovitz** [comment]
@paradiseduo Also, the package does not lend itself well to being used as a library rather than a compiled executable. Most of the functions are labeled as `private` which would make it difficult for us to use it without forking and creating our own version.

**Comment by paradiseduo** [comment]
> Do you have an ETA on the removal feature?

a5cbc6ae5d819b4c185e4fe3604a9bbcf9c4f5a2

**Comment by paradiseduo** [comment]
> @paradiseduo Also, the package does not lend itself well to being used as a library rather than a compiled executable. Most of the functions are labeled as `private` which would make it difficult for us to use it without forking and creating our own version.

58f4c4ce5dd7c7ba7954d6b740999e098500d640
Use Injection.framework

**Comment by amirsaam** [comment]
We appreciate your efforts buddy!

**Comment by IsaacMarovitz** [comment]
> > @paradiseduo Also, the package does not lend itself well to being used as a library rather than a compiled executable. Most of the functions are labeled as `private` which would make it difficult for us to use it without forking and creating our own version.
> 
> [58f4c4c](https://github.com/paradiseduo/inject/commit/58f4c4ce5dd7c7ba7954d6b740999e098500d640) Use Injection.framework

@paradiseduo Can you turn this framework into a Swift Package so we can avoid copying directly

Implementation started in https://github.com/PlayCover/PlayCover/pull/554

**Comment by paradiseduo** [comment]
> > > @paradiseduo Also, the package does not lend itself well to being used as a library rather than a compiled executable. Most of the functions are labeled as `private` which would make it difficult for us to use it without forking and creating our own version.
> > 
> > 
> > [58f4c4c](https://github.com/paradiseduo/inject/commit/58f4c4ce5dd7c7ba7954d6b740999e098500d640) Use Injection.framework
> 
> @paradiseduo Can you turn this framework into a Swift Package so we can avoid copying directly
> 
> Implementation started in [PlayCover/PlayCover#554](https://github.com/PlayCover/PlayCover/pull/554)

Package.swift like this:
```
// swift-tools-version: 5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "Test",
    products: [
        .executable(
            name: "Test",
            targets: ["Test"]),
    ],
    dependencies: [
         .package(url: "https://github.com/paradiseduo/inject", from: "1.0.0"),
    ],
    targets: [
        .target(
            name: "Test",
            dependencies: [.product(name: "Injection", package: "inject"),]),
        .testTarget(
            name: "TestTests",
            dependencies: ["Test"]),
    ]
)

```

Use like this:
```
import injection

Inject.injectMachO(machoPath: "", cmdType: LC_Type.LOAD_DYLIB, backup: false, injectPath: "") { result in
    
}
```

**Comment by amirsaam** [comment]
Hello @paradiseduo,

Thanks to @IsaacMarovitz we already switched to your framework and acknowledged in PlayCover repo readme.
Thanks you for your effort!

Regards,
On behalf of PlayCover Community
